name: Java CI-CD with Maven

on:
  workflow_dispatch:
  #push:
    #branches: [ "master" ]

jobs:
  build_maven:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload build artifacts       
      uses: actions/upload-artifact@v3      
      with:        
        name: dockeransible.war        
        path: target/dockeransible.war
    
  Image_build__and_push:
    needs: build_maven
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: arka111/webapps:${{ steps.date.outputs.date }}
          
  Ansible_deploy:
    needs: Image_build__and_push
    runs-on: ubuntu-latest
    steps:
    
    -
        name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
    - 
        name: Ansible playbook
        uses: jawher/action-ansible@2.9.7
        env:
          ANSIBLE_SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          args: ansible-playbook -i /deploy/inventories/hosts.yml /deploy/docker-deploy.yml --extra-vars DOCKER_TAG=${{ steps.date.outputs.date }} -vvv
