name: Java CI-CD with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload build artifacts       
      uses: actions/upload-artifact@v3      
      with:        
        name: dockeransible.war        
        path: target/dockeransible.war
    
  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d--%M-%S')"
      -
        name: Checkout 
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: arka111/webapps:${{ steps.date.outputs.date }}
          
      - 
        name: Ansible playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
        # Required, playbook filepath
          playbook: deploy-docker.yml
        # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
        # Optional, literal inventory file contents
          inventory: |
            [all]
            34.220.218.245

            [group1]
            34.220.218.245
          options: |
            --extra-vars DOCKER_TAG=${{ steps.date.outputs.date }}
            --limit group1
            --verbose
